version: '3'
services:
  api:
    build: ./src
    restart: always
    container_name: api
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ./src:/api

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  celery_worker:
    container_name: celery_worker
    build: ./src
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - ./src:/api
    restart: always
    depends_on:
      - redis
      - api

  flower:
    container_name: flower
    build: ./src
    command: celery -A celery_worker.celery flower --port=5555
    ports:
      - 5555:5555
    restart: always
    depends_on:
      - redis
      - api
      - celery_worker